AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD Pipeline with Conformity Scan and Deploy (GitHub Source via CodeStar Connection)

Resources:
  # ----------------------------
  # S3 Bucket for CodePipeline Artifacts
  # ----------------------------
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "cicd-artifacts-${AWS::AccountId}-${AWS::Region}"

  # ----------------------------
  # IAM Role for CodePipeline
  # ----------------------------
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # ----------------------------
  # IAM Role for CloudFormation execution
  # ----------------------------
  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # ----------------------------
  # IAM Role for CodeBuild
  # ----------------------------
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # ----------------------------
  # CodeBuild Project
  # ----------------------------
  MyBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: MyBuildProject
      Source:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        EnvironmentVariables:
          - Name: CONFORMITY_API_KEY
            Value: "YOUR_API_KEY_HERE"
          - Name: CONFORMITY_REGION
            Value: "us-west-2"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE

  # ----------------------------
  # CodePipeline
  # ----------------------------
  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: MyBuildProject
    Properties:
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: arn:aws:codeconnections:us-east-1:927311782751:connection/a92986bb-9866-4284-aea3-763947b7fe31
                FullRepositoryId: jonathannkrumah/CI-CD-PIPELINE-PROJECT
                BranchName: main
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref MyBuildProject
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: DeployCFN
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: DeployedAppStack
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
              RunOrder: 1
