AWSTemplateFormatVersion: "2010-09-09"
Description: Sample CloudFormation template for CI/CD pipeline testing

Resources:
  SampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sample-cicd-bucket-123456

  SampleIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SampleBuildRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
