AWSTemplateFormatVersion: "2010-09-09"
Description: Sample CloudFormation template for CI/CD pipeline testing

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

Resources:
  # ---------- S3 Bucket ----------
  SampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sample-cicd-bucket-123456

  # ---------- IAM Role ----------
  SampleIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SampleBuildRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # ---------- EC2 Security Group ----------
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP access only"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # ---------- EC2 Instance ----------
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 in us-east-1
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: CI-CD-EC2-Instance-NoKey

Outputs:
  EC2InstanceId:
    Description: "Instance ID of the deployed EC2"
    Value: !Ref MyEC2Instance

  EC2PublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicIp

  SampleS3BucketName:
    Description: "Name of the sample S3 bucket"
    Value: !Ref SampleS3Bucket
